PAGE_DESCRIPTION_OVERRIDES = {
    "Alan Wake": "A story-driven action thriller in which novelist Alan Wake battles a supernatural darkness in Bright Falls while searching for his missing wife.",
    "Alien: Isolation": "A survival horror game set fifteen years after Alien, following Amanda Ripley as she hides, scavenges, and survives aboard Sevastopol Station.",
    "Amnesia: A Machine for Pigs": "A first-person horror adventure about industrial nightmares, disturbing visions, and a desperate search for family in Victorian London.",
    "Amnesia: Rebirth": "A narrative horror journey through the Algerian desert where Tasi Trianon must survive fear, loss, and something far worse than death.",
    "Amnesia: The Bunker": "A tense survival horror game set in a World War I bunker where every bullet, every noise, and every decision can attract the creature hunting you.",
    "Amnesia: The Dark Descent": "A landmark first-person horror game about memory loss, crumbling sanity, and the terror hiding inside Brennenburg Castle.",
    "Assassin's Creed Unity": "Explore revolutionary Paris as Arno, master parkour across a dense open city, and uncover a conspiracy behind the chaos of the French Revolution.",
    "Atomic Heart": "A retro-futuristic action shooter where rogue machines, secret experiments, and a collapsing utopia turn a Soviet research complex into a nightmare.",
    "Baldur's Gate 3": "Gather your party, shape your own path through the Forgotten Realms, and make choices that define friendship, betrayal, sacrifice, and power.",
    "Batman: Arkham Asylum": "Step into Gotham's most dangerous institution as Batman and use stealth, gadgets, and combat mastery to stop Joker's takeover.",
    "Batman: Arkham City": "Batman is trapped inside a massive prison district of Gotham, where predators, criminals, and old enemies rule the streets.",
    "Batman: Arkham Knight": "The Scarecrow launches his final assault on Gotham, forcing Batman to face a collapsing city, the Batmobile, and the mysterious Arkham Knight.",
    "Batman: Arkham Origins": "A younger Batman faces assassins, gang violence, and a city-wide manhunt on a brutal Christmas Eve in Gotham.",
    "Battlefield 1 Revolution": "Fight through the chaos of World War I in large-scale battles with infantry combat, vehicles, and dramatic frontline warfare.",
    "Battlefield 4": "A modern military shooter built around destructive environments, massive battles, and a blockbuster single-player campaign.",
    "Battlefield V": "Return to World War II with squad-based combat, large battlefields, and combined arms warfare across land, sea, and air.",
    "BioShock 2": "Return to Rapture as a Big Daddy and fight through the ruined underwater city with plasmids, weapons, and twisted ideology.",
    "Black Myth: Wukong": "A myth-inspired action RPG that follows the Destined One through dangerous battles, ancient legends, and powerful transformations.",
    "Buckshot Roulette": "A short horror strategy game that turns a deadly game of chance into a tense duel against a shotgun and pure bad luck.",
    "Chained Together": "A co-op climbing challenge where players are physically linked together and every jump can save the team or ruin the run.",
    "Civilization VI": "Build an empire that stands the test of time by expanding cities, advancing technology, mastering diplomacy, and winning on your own terms.",
    "Counter-Strike 2": "A competitive tactical shooter focused on precise gunplay, team coordination, map control, and high-stakes rounds.",
    "Cyberpunk 2077": "Become a mercenary outlaw in Night City, take on dangerous jobs, and shape V's story in a neon-soaked open-world RPG.",
    "Darkwood": "A top-down survival horror experience built around exploration, scarce resources, and the growing dread of the woods after dark.",
    "Detroit: Become Human": "A cinematic interactive drama where the lives of three androids intertwine and your choices shape the future of an entire city.",
    "Dota 2": "A deep competitive MOBA where two teams of five clash, master unique heroes, and fight to destroy the enemy Ancient.",
    "Elden Ring": "Rise as a Tarnished and explore a vast fantasy world filled with hidden paths, deadly bosses, and the shattered power of the Elden Ring.",
    "Factorio": "Land on an alien world, automate production, expand your factory, and turn raw resources into an industrial machine.",
    "Far Cry 3": "Stranded on a lawless tropical island, Jason Brody must survive pirates, warlords, and his own descent into violence.",
    "Fallout 4": "Leave Vault 111 and explore a devastated Boston in an open-world RPG built around survival, factions, settlements, and freedom of choice.",
    "Fallout: New Vegas": "A Mojave wasteland RPG where shifting factions, personal ambition, and player choice shape the future of New Vegas.",
    "Fears to Fathom: Carson House": "A short psychological horror story about an ordinary night job that slowly turns into something deeply unsettling.",
    "Fears to Fathom: Home Alone": "A tense horror episode about being left home alone and realizing that something feels very wrong.",
    "Fears to Fathom: Ironbark Lookout": "Take a quiet fire lookout job in the woods and discover that the isolation around you is not as peaceful as it seems.",
    "Fears to Fathom: Norwood Hitchhike": "A roadside horror story where a late-night motel stop and a long drive turn into an increasingly dangerous situation.",
    "Fears to Fathom: Woodbury Getaway": "A seemingly harmless weekend trip turns into a suspenseful horror experience built around ordinary places and rising fear.",
    "Firewatch": "A first-person mystery set in the Wyoming wilderness, where one summer of isolation leads to secrets, tension, and emotional discovery.",
    "FlatOut 2": "An arcade racing game full of speed, destruction, ragdoll crashes, and aggressive tracks built for chaos.",
    "Grand Theft Auto III - Definitive Edition": "Return to Liberty City and rise through the criminal underworld in the game that defined open-world crime sandboxes.",
    "Grand Theft Auto IV": "A darker crime story set in Liberty City, where immigrant veteran Niko Bellic searches for revenge and a new life.",
    "Grand Theft Auto: San Andreas - Definitive Edition": "Follow Carl Johnson across a sprawling state of gangs, betrayal, and street-level crime in one of Rockstar's most iconic adventures.",
    "Grand Theft Auto V": "Switch between three criminals and pull off escalating heists in a sprawling open-world take on modern Southern California.",
    "Grand Theft Auto: Vice City - Definitive Edition": "Step into a neon-soaked 1980s crime story as Tommy Vercetti climbs from hired thug to kingpin of Vice City.",
    "Hades": "Fight your way out of the Underworld in a fast-paced rogue-like where each run, upgrade, and conversation pushes the story forward.",
    "Helldivers 2": "Join a squad of elite soldiers, drop into hostile planets, and bring overwhelming firepower to a co-op war for Super Earth.",
    "Hitman 2: Silent Assassin": "Return to stealth assassination as Agent 47 and complete global contracts with patience, disguise, and precision.",
    "Hitman: Absolution": "Agent 47 is betrayed and hunted, forcing him into a more personal and dangerous series of stealth missions.",
    "Hitman: Blood Money": "Master open-ended assassination sandboxes where planning, disguise, accidents, and escape are all part of the contract.",
    "Hitman: Codename 47": "The first chapter in Agent 47's career, introducing globe-spanning contracts, disguises, and methodical assassinations.",
    "Hitman: Contracts": "A darker, more intimate Hitman entry that revisits key missions and turns stealth kills into grim professional routine.",
    "Hitman World of Assassination": "Travel across richly detailed sandbox locations, study your targets, and eliminate them with absolute freedom and style.",
    "Hogwarts Legacy": "Step into the wizarding world, attend Hogwarts in the 1800s, and explore a magical open world full of spells, secrets, and danger.",
    "Just Cause": "Cause large-scale destruction in a tropical dictatorship using grappling movement, stunts, and explosive open-world action.",
    "Mafia II": "A story-driven crime drama following Vito Scaletta through the post-war underworld of Empire Bay.",
    "Mafia III": "After betrayal and loss, Lincoln Clay wages a violent war against the criminal empire that took everything from him.",
    "Manhunt": "A brutal stealth action game where survival depends on staying hidden, striking fast, and enduring a twisted snuff-film hunt.",
    "Max Payne": "A noir third-person shooter about revenge, painkillers, and bullet-time gunfights in a crime-ridden New York.",
    "Max Payne 2": "A stylish action thriller that deepens Max's tragic story with cinematic gunplay, slow-motion combat, and a doomed romance.",
    "Max Payne 3": "An older, broken Max fights through kidnappings, corruption, and heavy gunfights in the violent streets of Sao Paulo.",
    "Medal of Honor": "A military shooter focused on modern warfare, special operations, and grounded combat inspired by real-world conflicts.",
    "Microsoft Flight Simulator": "Pilot aircraft across a richly simulated world built around real geography, weather, and global aviation detail.",
    "Mimic Search": "A small-scale horror experience built around unsettling discovery, strange spaces, and the fear of being watched.",
    "Missing Hiker": "A short first-person horror story about searching for a missing person and walking straight into something far more disturbing.",
    "Mouthwashing": "A surreal psychological horror game that mixes dread, strange imagery, and unraveling tension in a deeply uncomfortable setting.",
    "Outlast": "Investigative journalist Miles Upshur enters Mount Massive Asylum and finds only madness, violence, and the need to run.",
    "Penumbra: Black Plague": "A first-person horror adventure that continues Philip's desperate journey through isolation, infection, and psychological collapse.",
    "Penumbra: Overture": "Explore an abandoned mining complex and uncover the first layers of a cold, atmospheric horror mystery.",
    "Phasmophobia": "A co-op ghost-hunting horror game where players investigate haunted locations, identify spirits, and try to get out alive.",
    "Portal": "Use the portal gun to bend space, solve elegant puzzles, and survive a deadly experiment run by GLaDOS.",
    "Portal 2": "A first-person puzzle adventure with portals, inventive test chambers, co-op missions, and a sharp comedic sci-fi story.",
    "Prey": "Wake up aboard Talos I and survive an alien outbreak in an immersive sci-fi thriller built around powers, choice, and exploration.",
    "Red Dead Redemption": "An open-world western that follows John Marston across the fading frontier as he hunts the men from his former gang.",
    "Red Dead Redemption 2": "Live through the last days of the Van der Linde gang in a sprawling western about loyalty, survival, and a changing America.",
    "Resident Evil 0": "Uncover the events before the mansion incident in a survival horror prequel built around fear, puzzles, and limited resources.",
    "Resident Evil 2": "Survive the fall of Raccoon City as Leon or Claire in a horror remake built around tension, exploration, and desperate combat.",
    "Resident Evil 4": "Rescue the president's daughter in a landmark action horror game built around pressure, pacing, and brutal encounters.",
    "Rise of the Tomb Raider": "Join Lara Croft on a globe-spanning expedition filled with ancient tombs, harsh wilderness, and dangerous enemies.",
    "Rust": "A brutal multiplayer survival game about gathering resources, building shelter, raiding rivals, and surviving other players.",
    "Silent Hill 2": "A psychological horror journey into grief, guilt, and memory as James Sunderland searches the fog-covered town for his wife.",
    "Silent Hill f": "A new entry in the Silent Hill series that shifts the horror to 1960s Japan with beauty, dread, and something deeply wrong beneath the surface.",
    "SOMA": "A science-fiction horror experience that explores identity, consciousness, and survival at the bottom of the ocean.",
    "Spider-Man Remastered": "Swing through Marvel's New York as Peter Parker and balance acrobatic combat, open-world heroics, and a personal story.",
    "Stardew Valley": "Build a farm, befriend the locals, explore caves, and create a new life in a peaceful countryside community.",
    "Subnautica": "Crash-land on an alien ocean world and dive deeper for resources, secrets, and survival beneath the surface.",
    "Terraria": "Dig, build, fight, and explore a huge 2D sandbox world full of crafting, bosses, secrets, and adventure.",
    "That Which Gave Chase": "A horror experience built around pursuit, tension, and the feeling that something unseen is never far behind.",
    "The Last of Us Part I": "Travel across a ruined America with Joel and Ellie in a story-driven survival action game about loss, trust, and endurance.",
    "The Witcher 3: Wild Hunt": "Become Geralt of Rivia and track the Child of Prophecy across a war-torn world filled with monsters, kingdoms, and difficult choices.",
    "Tomb Raider": "An origin story for Lara Croft that turns a disastrous expedition into a fight for survival, discovery, and resilience.",
    "Tomb Raider: Anniversary": "A modern retelling of Lara Croft's first adventure, focused on tomb exploration, platforming, and ancient mysteries.",
    "Tomb Raider: Legend": "A globe-trotting Lara Croft adventure built around agile movement, cinematic action, and mythic artifacts.",
    "Tomb Raider: Underworld": "Follow Lara across dangerous ruins and hidden worlds as she searches for answers about her family and ancient power.",
}
